#ifndef _CONFIG_H
#define _CONFIG_H

#include "hardware/stm32f10x_conf.h"

#define CONFIG_MODULE_LED	1
#define CONFIG_MODULE_DBG_UART	1
#define CONFIG_MODULE_SX126X	1
#define CONFIG_MODULE_OLED	1
#define CONFIG_MODULE_DI	1
#define CONFIG_MODULE_KEY	1

/* Clock source */
#define CONFIG_RCC_HSI		0
#define CONFIG_RCC_HSE		1
#define CONFIG_RCC_PLL		0
#if (CONFIG_RCC_HSI) && (CONFIG_RCC_HSE) && (CONFIG_RCC_PLL)
#error "Please choose one SYSCLK source"
#endif


/* LED */
#if CONFIG_MODULE_LED
#define CONFIG_LED_1_GPIO_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_LED_1_GPIO_CLK		RCC_APB2Periph_GPIOC
#define CONFIG_LED_1_GPIO_PORT		GPIOC
#define CONFIG_LED_1_GPIO_PIN		GPIO_Pin_13
#endif /* CONFIG_MODULE_LED */

/* Debug uart */
#if CONFIG_MODULE_DBG_UART
#define CONFIG_DBG_UART			USART1
#define CONFIG_DBG_UART_CLK_FUN		RCC_APB2PeriphClockCmd
#define CONFIG_DBG_UART_CLK		RCC_APB2Periph_USART1
#define CONFIG_DBG_UART_BAUDRATE	115200

#define CONFIG_DBG_UART_TX_GPIO_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_DBG_UART_TX_GPIO_CLK	RCC_APB2Periph_GPIOA
#define CONFIG_DBG_UART_TX_GPIO_PORT	GPIOA
#define CONFIG_DBG_UART_TX_GPIO_PIN	GPIO_Pin_9

#define CONFIG_DBG_UART_RX_GPIO_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_DBG_UART_RX_GPIO_CLK	RCC_APB2Periph_GPIOA
#define CONFIG_DBG_UART_RX_GPIO_PORT	GPIOA
#define CONFIG_DBG_UART_RX_GPIO_PIN	GPIO_Pin_10
#endif /* CONFIG_MODULE_DBG_UART */

#if CONFIG_MODULE_SX126X
//NSS	SCK	MISO	MOSI	NRST	TXEN	RXEN	BUSY	DIO1	DIO2
//PA4	PA5	PA6	PA7	PB5	PB4	PB3	PA15	PB0	PB1

#define CONFIG_SX126X_SPI		SPI1
#define CONFIG_SX126X_CLK_FUN		RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_CLK		RCC_APB2Periph_SPI1

#define CONFIG_SX126X_CS_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_CS_CLK		RCC_APB2Periph_GPIOA
#define CONFIG_SX126X_CS_PORT		GPIOA
#define CONFIG_SX126X_CS_PIN		GPIO_Pin_4

#define CONFIG_SX126X_SCK_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_SCK_CLK		RCC_APB2Periph_GPIOA
#define CONFIG_SX126X_SCK_PORT		GPIOA
#define CONFIG_SX126X_SCK_PIN		GPIO_Pin_5

#define CONFIG_SX126X_MISO_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_MISO_CLK		RCC_APB2Periph_GPIOA
#define CONFIG_SX126X_MISO_PORT		GPIOA
#define CONFIG_SX126X_MISO_PIN		GPIO_Pin_6

#define CONFIG_SX126X_MOSI_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_MOSI_CLK		RCC_APB2Periph_GPIOA
#define CONFIG_SX126X_MOSI_PORT 	GPIOA
#define CONFIG_SX126X_MOSI_PIN		GPIO_Pin_7

#define CONFIG_SX126X_NRST_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_NRST_CLK		RCC_APB2Periph_GPIOB
#define CONFIG_SX126X_NRST_PORT 	GPIOB
#define CONFIG_SX126X_NRST_PIN		GPIO_Pin_5

#define CONFIG_SX126X_TXEN_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_TXEN_CLK		RCC_APB2Periph_GPIOB
#define CONFIG_SX126X_TXEN_PORT 	GPIOB
#define CONFIG_SX126X_TXEN_PIN		GPIO_Pin_4

#define CONFIG_SX126X_RXEN_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_RXEN_CLK		RCC_APB2Periph_GPIOB
#define CONFIG_SX126X_RXEN_PORT 	GPIOB
#define CONFIG_SX126X_RXEN_PIN		GPIO_Pin_3

#define CONFIG_SX126X_BUSY_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_BUSY_CLK		RCC_APB2Periph_GPIOA
#define CONFIG_SX126X_BUSY_PORT 	GPIOA
#define CONFIG_SX126X_BUSY_PIN		GPIO_Pin_15

#define CONFIG_SX126X_DIO1_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_DIO1_CLK		RCC_APB2Periph_GPIOB
#define CONFIG_SX126X_DIO1_PORT 	GPIOB
#define CONFIG_SX126X_DIO1_PIN		GPIO_Pin_0
#define CONFIG_SX126X_DIO1_EXTI_PORTSRC	GPIO_PortSourceGPIOB
#define CONFIG_SX126X_DIO1_EXTI_PINSRC	GPIO_PinSource0
#define CONFIG_SX126X_DIO1_EXTI_LINE	EXTI_Line0
#define CONFIG_SX126X_DIO1_EXTI_IRQ	EXTI0_IRQn
#define CONFIG_SX126X_DIO1_EXTI_ISR	EXTI0_IRQHandler

#define CONFIG_SX126X_DIO2_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_SX126X_DIO2_CLK		RCC_APB2Periph_GPIOB
#define CONFIG_SX126X_DIO2_PORT 	GPIOB
#define CONFIG_SX126X_DIO2_PIN		GPIO_Pin_1
#define CONFIG_SX126X_DIO2_EXTI_PORTSRC GPIO_PortSourceGPIOB
#define CONFIG_SX126X_DIO2_EXTI_PINSRC	GPIO_PinSource1
#define CONFIG_SX126X_DIO2_EXTI_LINE	EXTI_Line1
#define CONFIG_SX126X_DIO2_EXTI_IRQ	EXTI1_IRQn
#define CONFIG_SX126X_DIO2_EXTI_ISR	EXTI1_IRQHandler

#endif /* CONFIG_MODULE_SX126X */

#if CONFIG_MODULE_OLED
// SCLK, SDIN, RST, DC, CS
#define CONFIG_OLED_SCLK_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_OLED_SCLK_CLK		RCC_APB2Periph_GPIOB
#define CONFIG_OLED_SCLK_PORT		GPIOB
#define CONFIG_OLED_SCLK_PIN		GPIO_Pin_12

#define CONFIG_OLED_SDIN_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_OLED_SDIN_CLK		RCC_APB2Periph_GPIOB
#define CONFIG_OLED_SDIN_PORT		GPIOB
#define CONFIG_OLED_SDIN_PIN		GPIO_Pin_13

#define CONFIG_OLED_RST_CLK_FUN		RCC_APB2PeriphClockCmd
#define CONFIG_OLED_RST_CLK		RCC_APB2Periph_GPIOB
#define CONFIG_OLED_RST_PORT		GPIOB
#define CONFIG_OLED_RST_PIN		GPIO_Pin_14

#define CONFIG_OLED_DC_CLK_FUN		RCC_APB2PeriphClockCmd
#define CONFIG_OLED_DC_CLK		RCC_APB2Periph_GPIOB
#define CONFIG_OLED_DC_PORT		GPIOB
#define CONFIG_OLED_DC_PIN		GPIO_Pin_15
#endif /* CONFIG_MODULE_OLED */

#if CONFIG_MODULE_DI
#define CONFIG_DI1_GPIO_PIN              GPIO_Pin_8
#define CONFIG_DI1_GPIO_PORT             GPIOA
#define CONFIG_DI1_GPIO_CLK              RCC_APB2Periph_GPIOA
#define CONFIG_DI1_GPIO_CLK_FUN          RCC_APB2PeriphClockCmd
#endif /* CONFIG_MODULE_DI */


#if CONFIG_MODULE_KEY
#define CONFIG_KEY1_GPIO_PIN		GPIO_Pin_6
#define CONFIG_KEY1_GPIO_PORT		GPIOB
#define CONFIG_KEY1_GPIO_CLK		(RCC_APB2Periph_GPIOB | RCC_APB2Periph_AFIO)
#define CONFIG_KEY1_GPIO_CLK_FUNC	RCC_APB2PeriphClockCmd

#define CONFIG_KEY1_EXTI_PORTSOURCE	GPIO_PortSourceGPIOB
#define CONFIG_KEY1_EXTI_PINSOURCE	GPIO_PinSource6
#define CONFIG_KEY1_EXTI_LINE		EXTI_Line6

#define CONFIG_KEY1_IRQ			EXTI9_5_IRQn
#define CONFIG_KEY1_IRQ_PRIO		3

#define CONFIG_KEY2_GPIO_PIN		GPIO_Pin_7
#define CONFIG_KEY2_GPIO_PORT		GPIOB
#define CONFIG_KEY2_GPIO_CLK		(RCC_APB2Periph_GPIOB | RCC_APB2Periph_AFIO)
#define CONFIG_KEY2_GPIO_CLK_FUNC	RCC_APB2PeriphClockCmd

#define CONFIG_KEY2_EXTI_PORTSOURCE	GPIO_PortSourceGPIOB
#define CONFIG_KEY2_EXTI_PINSOURCE	GPIO_PinSource7
#define CONFIG_KEY2_EXTI_LINE		EXTI_Line7
#endif /* CONFIG_MODULE_KEY*/

#endif /* _CONFIG_H */
