#ifndef _CONFIG_H
#define _CONFIG_H

#include "hardware/stm32f10x_conf.h"

#define CONFIG_MODULE_LED	1
#define CONFIG_MODULE_DBG_UART	1

/* Clock source */
#define CONFIG_RCC_HSI		0
#define CONFIG_RCC_HSE		1
#define CONFIG_RCC_PLL		0
#if (CONFIG_RCC_HSI) && (CONFIG_RCC_HSE) && (CONFIG_RCC_PLL)
#error "Please choose one SYSCLK source"
#endif


/* LED */
#if CONFIG_MODULE_LED
#define CONFIG_LED_1_GPIO_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_LED_1_GPIO_CLK		RCC_APB2Periph_GPIOC
#define CONFIG_LED_1_GPIO_PORT		GPIOC
#define CONFIG_LED_1_GPIO_PIN		GPIO_Pin_13
#endif /* CONFIG_MODULE_LED */

/* Debug uart */
#if CONFIG_MODULE_DBG_UART
#define CONFIG_DBG_UART			USART1
#define CONFIG_DBG_UART_CLK_FUN		RCC_APB2PeriphClockCmd
#define CONFIG_DBG_UART_CLK		RCC_APB2Periph_USART1
#define CONFIG_DBG_UART_BAUDRATE	115200

#define CONFIG_DBG_UART_TX_GPIO_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_DBG_UART_TX_GPIO_CLK	RCC_APB2Periph_GPIOA
#define CONFIG_DBG_UART_TX_GPIO_PORT	GPIOA
#define CONFIG_DBG_UART_TX_GPIO_PIN	GPIO_Pin_9

#define CONFIG_DBG_UART_RX_GPIO_CLK_FUN	RCC_APB2PeriphClockCmd
#define CONFIG_DBG_UART_RX_GPIO_CLK	RCC_APB2Periph_GPIOA
#define CONFIG_DBG_UART_RX_GPIO_PORT	GPIOA
#define CONFIG_DBG_UART_RX_GPIO_PIN	GPIO_Pin_10
#endif /* CONFIG_MODULE_DBG_UART */

#endif /* _CONFIG_H */
