#ifndef _M_ERR_H
#define _M_ERR_H

typedef enum {
	M_ERR_OK = 0,
	M_ERR_FAIL = -1,
	M_ERR_PARAM = -2,
	M_ERR_MEM = -3,
	M_ERR_TIMEOUT = -4,
	M_ERR_BUSY = -5,
	M_ERR_FLASH_PROGRAM_FAIL = -6,
	M_ERR_FLASH_RPOGRAM_DATA_NOMATCH = -7,
	M_ERR_FLASH_ERASE = -8,
	M_ERR_FW_ENV_NOT_TERMINATED = -9,
	M_ERR_FW_ENV_OVERFLOW = -10,
	M_ERR_FW_ENV_END = -11,
	M_ERR_FW_ENV_STRING_SPLIT = -12
} m_err_t;

#endif /* _M_ERR_H */
